// Code generated by "enumer -type=Format -trimprefix=Format"; DO NOT EDIT.

package libmangal

import (
	"fmt"
	"strings"
)

const _FormatName = "PDFImagesCBZ"

var _FormatIndex = [...]uint8{0, 3, 9, 12}

const _FormatLowerName = "pdfimagescbz"

func (i Format) String() string {
	i -= 1
	if i >= Format(len(_FormatIndex)-1) {
		return fmt.Sprintf("Format(%d)", i+1)
	}
	return _FormatName[_FormatIndex[i]:_FormatIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FormatNoOp() {
	var x [1]struct{}
	_ = x[FormatPDF-(1)]
	_ = x[FormatImages-(2)]
	_ = x[FormatCBZ-(3)]
}

var _FormatValues = []Format{FormatPDF, FormatImages, FormatCBZ}

var _FormatNameToValueMap = map[string]Format{
	_FormatName[0:3]:       FormatPDF,
	_FormatLowerName[0:3]:  FormatPDF,
	_FormatName[3:9]:       FormatImages,
	_FormatLowerName[3:9]:  FormatImages,
	_FormatName[9:12]:      FormatCBZ,
	_FormatLowerName[9:12]: FormatCBZ,
}

var _FormatNames = []string{
	_FormatName[0:3],
	_FormatName[3:9],
	_FormatName[9:12],
}

// FormatString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FormatString(s string) (Format, error) {
	if val, ok := _FormatNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FormatNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Format values", s)
}

// FormatValues returns all values of the enum
func FormatValues() []Format {
	return _FormatValues
}

// FormatStrings returns a slice of all String values of the enum
func FormatStrings() []string {
	strs := make([]string, len(_FormatNames))
	copy(strs, _FormatNames)
	return strs
}

// IsAFormat returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Format) IsAFormat() bool {
	for _, v := range _FormatValues {
		if i == v {
			return true
		}
	}
	return false
}
